centup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# This effectly forces the admin site's login to just use the same
# login mechanics as everyone else
admin.site.login = login_required(admin.site.login)

admin.autodiscover()

publisher_patterns =patterns('')
invite_patterns =patterns('')

urlpatterns = patterns('',
    url(r'', include('cover.urls')),
    #url(r'^admintools/', include('admin_tools.urls')),

    url(r'^login/?$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html'
    }, 'login'),

    url(r'^invite/check/?$', 'invites.views.enter_invite_code', name=
        'enter_invite_code'),

    url(r'^signup/?$', 'users.views.basic_info', name='signup'),

    url(r'^logout/?$', 'django.contrib.auth.views.logout', {
        'next_page': '/'
    }, 'logout'),

    url(r'^password/change/?$', 'django.contrib.auth.views.password_change', {
        'template_name': 'password/change.html',
        'post_change_redirect': '/user/dash/'
    }, 'password_change'),

    url(r'^password/reset/?$', 'django.contrib.auth.views.password_reset', {
        'template_name': 'password/reset.html',
    }, 'password_reset'),

    url(r'^password/reset/done/?$', 'django.contrib.auth.views.password_reset_done', {
        'template_name': 'password/done.html',
    }),
    url(r'^password/reset/confirm/(?P<uidb36>[\w\d]+)/(?P<token>[-\w\d]+)/?$', 'django.contrib.auth.views.password_reset_confirm', {
        'template_name': 'password/confirm.html',
    }),
    url(r'^password/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', {
        'template_name': 'password/complete.html',
    }),

    url(r'^welcome/?$', 'users.views.basic_info', name="welcome"),
    url(r'^welcome/1/?$', 'users.views.charity_selection', name="welcome1"),
    url(r'^welcome/2/?$', 'users.views.giving_options', name="welcome2"),
    url(r'^welcome/3/?$', 'users.views.payment_details', name="welcome3"),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^button', include('button.urls', namespace='button')),

    url(r'^publisher', include('publishers.urls')),
    url(r'^charity', include('charities.urls')),

    url(r'^news', include('news.urls')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'', include('social_auth.urls')),
    url(r'^invites/', include('invites.urls', namespace='invites')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),


    url(r'^favicon\.ico$',
     RedirectView.as_view(url=staticfiles_storage.url("favicon.ico").replace("%","%%"))),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(prefix='/media/')

news/urls.py
from django.conf.urls import patterns, include, url
#from news import views

urlpatterns = patterns('news.views',
    url(r'^/(?P<post_slug>[-_\w]+)/?$', 'post_detail', name='post'),
    url(r'^/$', 'post', name='posts'),
)

users/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('users.views',
    url(r'^dash/?$', 'dash', name='dash'),
)

users/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, \
                                    BaseUserManager
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from social_auth.models import UserSocialAuth

from invites.models import InviteCode


class UserManager(BaseUserManager):
    def create_user(self, email, username=None, password=None, **other):
        user = self.model(email=email, username=username)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password,  **other):
        user = self.model(email=email, username=username)
        user.set_password(password)
        user.is_admin=True
        user.save()
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=254, unique=True, blank=False)
    is_active  = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


    username  = models.CharField(max_length=254, blank=True,
        help_text="This is the name by which you will be seen publicly.")
    first_name   = models.CharField(max_length=128)
    last_name   = models.CharField(max_length=128)

    large_avatar = models.ImageField(upload_to='avatars/large/', blank=True,
        null=True, verbose_name='Avatar Image')

    account = models.OneToOneField('accounts.Account', related_name='user')

    preferred_charity = models.ForeignKey('charities.Charity', blank=True, null=True)
    default_donation_hc = models.PositiveIntegerField(default=50)

    preload_amount = models.DecimalField(
        default=Decimal('20.00'),
        blank=True,
        max_digits=settings.MAX_MONETARY_DIGITS,
        decimal_places=2
    )
    auto_reload = models.BooleanField(default=True)
    braintree_vault_token = models.CharField(max_length=255, blank=True, null=True)

    charity_quote = models.TextField(blank=True,
        verbose_name='Tell us why you support this charity ...',
        help_text="Your quote may be displayed on the charity's public profile page.")

    notify_on_low_balance = models.BooleanField(default=True,
        verbose_name="Notify me when my balance is low")
    notify_on_account_reload = models.BooleanField(default=True,
        verbose_name="Notify me when my account is reloaded")
    notify_on_charity_message = models.BooleanField(default=True,
        verbose_name="Notify me when a charity sends a message")
    periodic_updates = models.BooleanField(default=True,
        verbose_name="Send me periodic updates about CentUp")

    public_profile = models.BooleanField(default=True,
        verbose_name="Make my giving and content history public")

    invite = models.ForeignKey('invites.InviteCode', related_name='invited_users', null=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __unicode__(self):
        return self.get_full_name()

    objects = UserManager()

    @property
    def default_donation(self):
        if self.default_donation_hc % 2 != 0:
            raise ValueError("Default donation value can't be fractional!")
        return self.default_donation_hc / 2

    @default_donation.setter
    def default_donation(self, value):
        self.default_donation_hc = value * 2

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def has_password(self):
        return bool(self.password)

    @property
    def is_publisher(self):
        """For the moment this just means, has an approved publisher
        submitted"""
        return self.active_publishers.exists()

    @property
    def active_publishers(self):
        return self.publishers.filter(approved=True)

    def may_see_dashboard(self, publisher):
        return self.is_staff or \
            publisher in self.active_publishers

    @property
    def total_donations(self):
        return self._spent_cents_for_column('charity_amount_hc') + \
             self._spent_cents_for_column('publisher_amount_hc')

    def _spent_cents_for_column(self, col):
        return self.account.originated_donations.aggregate(
            amount_hc=models.Sum(col)
        )['amount_hc'] / 2.0


    MAX_DONATION = 1000
    @property
    def max_donation(self):
        if self.auto_reload:
            # When auto-reload is on, we can always donate whatever
            # we want!
            return self.MAX_DONATION
        else:
            return min(self.account.balance, self.MAX_DONATION)

users/views.py
import urlparse

import braintree


from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from accounts.forms import BraintreeTransactionForm, BraintreePaymentUpdateForm
from publishers.models import Publisher
from charities.models import Charity
from users import forms
from news.models import Post
from utils import credits

from postmonkey import PostMonkey


pm = PostMonkey('615d274bcc7d1c0092c9e3f8743010f6-us6', timeout=10)



@login_required
def dash(request):
    donation_settings_form = forms.UserDonationSettingsForm(
        instance=request.user)
    notification_settings_form = forms.UserNotificationSettingsForm(
        instance=request.user)

    if request.method == 'POST':
        # We have several forms here, must distinguish between them
        # (the braintree form btw only comes here via GET string, dealt with
        # just below)
        formtype = request.POST.get('formtype', None)
        if formtype == 'donation_settings_form':
            donation_settings_form = forms.UserDonationSettingsForm(
                request.POST, instance=request.user)
            if donation_settings_form.is_valid():
                donation_settings_form.save()

        elif formtype == 'notification_settings_form':
            notification_settings_form = forms.UserNotificationSettingsForm(
                request.POST, instance=request.user)
            if notification_settings_form.is_valid():
                notification_settings_form.save()

        else:
            raise Exception('Need a valid formtype (got %r)' % formtype)


    update_payment_form = None
    if request.user.braintree_vault_token:
        query = request.META['QUERY_STRING']
        if 'page' in request.GET:
            # this is a pagination query string... disregard
            query = ""
        update_payment_form = BraintreePaymentUpdateForm(
            result=query,
            vault_token=request.user.braintree_vault_token,
            redirect_url=reverse('users:dash')
        )
        if update_payment_form.is_success:
            update_payment_form.update_payment_info(request.user)

    news=Post.objects.all()[:1]
    #Added a simple featured publisher
    return render(request, 'user/dash.html', dict(
        featured_publishers=Publisher.objects.filter(approved=True, featured=True)[:9],
        #hacky treatment to avoid displaying zero centup credits
        recent_centups=request.user.account.originated_donations.all().filter(publisher_amount_hc__gte=1).order_by(
            '-created_at')[:10],
        all_centups=request.user.account.originated_donations.all().order_by(
            '-created_at'),
        donation_settings_form=donation_settings_form,
        notification_settings_form=notification_settings_form,
        update_payment_form=update_payment_form,
        braintree_url=braintree.TransparentRedirect.url(),
        news=news,
    ))

def basic_info(request):
	
    if request.user.is_authenticated():
        form_class = forms.SocialAuthUserForm
        form_kwargs = dict(instance=request.user)
    else:
        form_class = forms.PasswordSignUpForm
        form_kwargs = {}

    #invite = request.GET.get('invite', None)
    #if invite:
    #    request.session['saved_code']=invite
    #    form_kwargs['initial'] = {'invite':invite}

    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, **form_kwargs)
        if form.is_valid():
            #send an email address to mailchimp when someone signs up
            email_address = request.POST['email']
            pm.listSubscribe(id="d8ef093bd4", email_address=email_address)
            form.save()
            if not request.user.is_authenticated():
                # this is a new signup pw form
                new_user = authenticate(
                    username=form.cleaned_data['email'],
                    password=form.cleaned_data['password1'],
                )
                login(request, new_user)
            return HttpResponseRedirect(reverse('welcome1'))
    else:
        form = form_class(**form_kwargs)

    return render(request, 'user/basic_info.html', dict(
        form=form,
        publishers=Publisher.objects.filter(approved="TRUE").order_by('name'),
        charities=Charity.objects.filter(active="TRUE").order_by('name'),
        featured_publishers=Publisher.objects.filter(approved=True, featured=True)[:9]
    ))


@login_required
def charity_selection(request):
    if request.user.preferred_charity:
        # This user must be resuming their signup - just advance them
        # to the next step
        return HttpResponseRedirect(reverse('welcome2'))

    return render(request, 'user/charity_selection.html', dict(
        charities=Charity.objects.all(),
    ))

@login_required
def giving_options(request):
    if request.method == 'POST':
        form = forms.UserDonationSettingsForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('welcome3'))
    else:
        form = forms.UserDonationSettingsForm(instance=request.user)

    return render(request, 'user/giving_options.html', dict(
        form=form
    ))

@login_required
def payment_details(request):
    if request.user.braintree_vault_token:
        # This user already set their payment info, they can change
        # it in the dashboard
        return HttpResponseRedirect(reverse('users:dash'))
    try:
        form = BraintreeTransactionForm(request.META['QUERY_STRING'],
            redirect_url=reverse(payment_details),
            transaction_data={
                "type": "sale",
                "amount": request.user.preload_amount,
                "options": {
                    "submit_for_settlement": True,
                    "store_in_vault_on_success": True,
                    "add_billing_address_to_payment_method": True
                },
                "customer": {
                    "id": request.user.pk,
                    # The following are only being recorded to make
                    # manual reconciliation easier in braintree's
                    # command console
                    "first_name": request.user.first_name,
                    "last_name": request.user.last_name,
                    "email": request.user.email
                }
            })
        if form.is_success:
            form.authorize_funding(request.user)
            return HttpResponseRedirect(reverse('users:dash'))

        return render(request, 'user/payment_details.html', dict(
            form=form,
            braintree_url=braintree.TransparentRedirect.url()
        ))
    except braintree.exceptions.NotFoundError:
        # These almost always come from used up tokens - best to reset
        return HttpResponseRedirect(reverse(payment_details))

users/templates/user/basic_info.html
{% extends "base.html" %}
{% load staticfiles %}}
{% block head %}

{% endblock head %}

{% block content %}

<style type="text/css">
	.fileinputs input.file {
        position: relative;
        text-align: right;
        -moz-opacity:0 ;
        filter:alpha(opacity: 0);
        opacity: 0;
        z-index: 2;
    }

</style>

<div class="general-page generic-home-padding white signup">
	<div class="row">
		<!-- Left column -->
		<div class="span6 beige">
			<div class="generic-home-padding">
			 	<h1>
				{% block title %}
					{% if user.is_authenticated %}
					Confirm or Edit Your Account
					{% else %}
					Create Your Account
					{% endif %}
				{% endblock title %}
				</h1>

				{% if not user.is_authenticated %}
				<p>There's a few ways to get started. Sign-up using your facebook account or fill out the form below.</p>
				<!-- Commenting out the invite code HTML
				<div class="invite-code info-box">
					<div {% if form.invite.errors %}class="field_error"{% endif %}>
						<label><b>Invitation Code</b></label>
						{{form.invite}}
						{% for err in field.errors %}
						<span class="error_message">{{form.invite}}</span>
						{% endfor %}
					</div>
					<div class="no-invite-code">
						No code? <a href="/">Get One.</a>
					</div>
				</div>
				-->
				{% endif %}

				{% if form.errors %}
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">×</button>
					
					<h4>Oh hey, we found some errors:</h4><br>
					{% for field in form %}
					  {% if field.errors %}
					  <li><strong>{{ field.label }}:</strong> {{ field.errors|striptags }}</li>
					  {% endif %}
					{% endfor %}
				</div>
				{% endif %}


				<div class="fb-option">
					<p><strong>Use Facebook</strong></p>
					<a href="{% url 'socialauth_begin' 'facebook' %}"><img src="{% static 'images/fbconnect.png' %}" alt="Connect with Facebook" /></a>
				</div>

				<p><strong>Enter Your Information</strong></p>
			 	<form method="post" action="{% url 'welcome' %}" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.non_field_errors }}
					
					<!--No more Django forms API -->
					<ul class="signup-user">
						<!-- Email -->
						<li>
						  <div {% if form.email.errors %}class="field_error"{% endif %}>
							<label>Email</label>
							{{form.email}}
							{% for err in field.errors %}
							<span class="error_message">{{form.email}}</span>
							{% endfor %}
						  </div>
						</li>
						
						<!-- User name -->
						<li>
							<div {% if form.username.errors %}class="field_error"{% endif %}>
								<label>Username</label>
								{{form.username}}
								{% for err in field.errors %}
								<span class="error_message">{{form.username}}</span>
								{% endfor %}
							  </div>
						</li>
						
						<!-- Password -->
						{% if form.password1 %}
						<li>
							<div {% if form.password1.errors %}class="field_error"{% endif %}>
								<label for="id_password1">{{form.password1.label}}</label>
								{{form.password1}}
								{% for err in field.errors %}
								<span class="error_message">{{form.password1}}</span>
								{% endfor %}
							  </div>
						</li>
						<li>
							<div {% if form.password2.errors %}class="field_error"{% endif %}>
								<label for="id_password2">{{form.password2.label}}</label>
								{{form.password2}}
								{% for err in field.errors %}
								<span class="error_message">{{form.password2}}</span>
								{% endfor %}
							</div>
						</li>
						{% endif %}
						
						<!-- First Name -->
						<li>
							<div {% if form.first_name.errors %}class="field_error"{% endif %}>
								<label>First Name</label>
								{{form.first_name}}
								{% for err in field.errors %}
								<span class="error_message">{{form.first_name}}</span>
								{% endfor %}
							  </div>
						</li>
						
						<!-- Last Name -->
						<li>
							<div {% if form.last_name.errors %}class="field_error"{% endif %}>
								<label>Last Name</label>
								{{form.last_name}}
								{% for err in field.errors %}
								<span class="error_message">{{form.last_name}}</span>
								{% endfor %}
							  </div>
						</li>
						
						<!-- Profile Image -->
						<li>
							<br/>
							<label>Profile Image</label>
							<span class="file-avatar">
								{% if user.social_auth %}
									{% if user.large_avatar %}
									<img src="{{user.large_avatar.url}}" alt="user avatar"/>
									{% endif %}
									<div class="fileinputs">
								        {{form.large_avatar}}
								        <div class="fakefile">
								            <input type="button" class="btn btn-file" value="Change Image" />
								        </div>
								    </div>
								{% else %}
								<!--Begin Nicely Styled Image Upload -->
									{{form.large_avatar.errors}}
										<div class="fileupload fileupload-new" data-provides="fileupload">
											<div class="fileupload-new thumbnail" style="width: 50px; height: 50px;"><img src="http://www.placehold.it/50x50/EFEFEF/AAAAAA" /></div>
											<div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div>
											<span class="btn btn-file"><span class="fileupload-new">Select Image</span><span class="fileupload-exists">Change</span>{{form.large_avatar}}</span>
	                                         <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
	                                     </div>
	                             <!--End Nicely Styled Image Upload -->						
							</span>
							{% endif %}
						</li>
						<!-- Terms -->
						<li>
							<div {% if form.terms_and_conditions.errors %}class="field_error"{% endif %}>
								{{form.terms_and_conditions}}
								<label class="terms">I agree to the CentUp <a href="{% url 'terms' %}" target="_blank">Terms and Conditions</a> and I plan on doing lots of good on, for and with the internet.</label>
								{% for err in field.errors %}
								<span class="error_message">{{form.terms_and_conditions}}</span>
								{% endfor %}
								<span class="clearfix"></span>
							</div>
						</li>
					</ul>
					<br><br><br><input type="submit" class="btn-custom" name="submit" value="Create Account" />
				</form>
			 </div>
		</div>
		<!-- End Left Column -->
		
		<!-- Right Column -->
		<div class="span5">
			<div class="generic-home-padding">
				<div class="video">
				<h4>What is CentUp?</h4>
				<iframe src="http://player.vimeo.com/video/64957872" width="100%" height="213" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
			</div>
				
				<!--BEGIN Publisher List by approved and name -->
				<div class="row">
				<h4>Where Can You Use CentUp?</h4>
				<ul class="sidebar-list">
				{% for publisher in featured_publishers %}
					{% if publisher.approved %}
						<li>
							<a href="{{publisher.url}}" target="_blank"><img src="{{publisher.logo.url}}" style="width:70px;height:70px;" alt=""></a>
							<a href="{{publisher.url}}" target="_blank">{{publisher}}</a>
						</li>
						{% else %}
					{% endif %}
				{% endfor %}
				</ul>
				<span class="clearfix"></span>
			</div>
				<!--END Publisher List by approved and name -->
		<hr>
				<!--BEGIN Charity List by active and name -->
				<div class="row">
				<h4>Which Charities Can I Help?</h4>
				<ul class="sidebar-list">
				{% for charity in charities %}
					{% if charity.active %}
						<li>
							<a href="{{root_url}}/charity/{{charity.slug}}"><img src="{{charity.logo.url}}" style="width:70px;height:70px;" alt=""></a>
						</li>
					{% else %}
					{% endif %}
				{% endfor %}
				</ul>
			</div>
				<!--END Charity List by active and name -->
		</div>
		<!-- End Right Column -->
	</div>
	<!-- End Row -->

</div>
<!-- End Page -->
{% endblock content %}

users/templates/user/charity_selection.html
{% extends "base.html" %}
{% load utils %}

{% block content %}
<div class="general-page generic-home-padding white">
    <h1>Step 1 of 3 - {% block title %}Select Your Charity{% endblock title %}</h1>

    <p class="instructions">
        If you change your mind, you can select a new charity at any time from your dashboard.
    </p>


    {% include "charity/selector.html" %}
    <div class="nextstep">
        <a class="btn-custom" href="{% url 'welcome2' %}">
            Next Step
        </a>
    </div>

</div>

{% endblock content %}

users/templates/user/donation_controls.html
<style type="text/css">
    .auto-reload {
        background-color: #e6e1c2;
        color: #666;
        border-radius: 8px;
        padding: 12px;
    }

    .pre-load {
        margin-top: 40px;
    }

    .default-donation {
        margin-top: 40px;
        margin-bottom: 40px;
    }

    .question {
        height: 14px;
        width: 14px;
        padding: 3px;
        font-size: 12px;
        line-height: 12px;
    }

    .small {
        float: right;
        size: 12px;
    }

</style>



<div class="user-centup-tabs">

        <div class="pre-load">

           
                <label for="id_preload_amount">{{form.preload_amount.label}}:  
                    <div id="question" class="question btn" rel="popover" data-content="This is the amount you'll first load into your CentUp account. $10 is the minimum, but the higher number you set the less fees we all pay. Hooray!" data-original-title="Preload Amount">?</div>
                </label>
            {{form.preload_amount.errors}}
            {{form.preload_amount}} <span id="preload_amount_dollars"></span>
  
</div>

<div class="default-donation">

           
                <label for="id_default_donation_hc">{{form.default_donation_hc.label}}:
                    <div id="question3" class="question btn" rel="popover" data-content="This is the amount you'll pledge every time you click the CentUp button. (Yep it's just a click). Don't worry you'll be able to increase your donation directly on our button if you find content that is super good." data-original-title="Default CentUp amount">?</div>
                </label>
            {{form.default_donation_hc.errors}}

            {{form.default_donation_hc}}
            <span class="credit-amount" id="default_donation_credits"></span> 
            <span class="credit-label"> (CentUp Credits)</span>    
   </div>


<div class="auto-reload">
    <p>
        <label for="id_auto_reload"></label>
        {{form.auto_reload.errors}}
        {{form.auto_reload}} <span> Auto-reload my account each time I run out of CentUp Credits. Your credit card will be charged with your Preload Amount. You can easily turn this feature on and off using the admin dashboard. </span>
        <!--<div id="question" class="question btn" rel="popover" data-content="This ensures your account replenishes automatically when you hit zero. No one likes zero." data-original-title="Auto Reload">?</div>-->
    </p>
</div>

</div>

users/templates/user/giving_options.html
{% extends "base.html" %}
{% load utils %}

{% block head %}

{% endblock head %}

{% block content %}
<div class="general-page generic-home-padding white">
<h1>Step 2 of 3 - {% block title %}Donation Settings{% endblock title %}</h1>
<form method="post" action="{% url 'welcome2' %}">
    {% csrf_token %}
    {% include "user/donation_controls.html" %}

    <div class="nextstep">
        <input type="submit" class="btn-custom" name="submit"  value="Next Step" />
    </div>
</form>
</div>

{% endblock content %}

users/templates/user/info.html
{% extends "base.html" %}

{% block content %}
{% if new %}
    <h1>Confirm your new account</h1>
{% else %}
    <h1>Edit your account
{% endif %}


<form method="post" action="{% url 'users:info' %}">
    {% csrf_token %}
    <table class="form">
    {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-primary" name="submit"  value="Continue" />
    <input type="hidden" name="new" value="{{ new }}" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock content %}