centup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# This effectly forces the admin site's login to just use the same
# login mechanics as everyone else
admin.site.login = login_required(admin.site.login)

admin.autodiscover()

publisher_patterns =patterns('')
invite_patterns =patterns('')

urlpatterns = patterns('',
    url(r'', include('cover.urls')),
    #url(r'^admintools/', include('admin_tools.urls')),

    url(r'^login/?$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html'
    }, 'login'),

    url(r'^invite/check/?$', 'invites.views.enter_invite_code', name=
        'enter_invite_code'),

    url(r'^signup/?$', 'users.views.basic_info', name='signup'),

    url(r'^logout/?$', 'django.contrib.auth.views.logout', {
        'next_page': '/'
    }, 'logout'),

    url(r'^password/change/?$', 'django.contrib.auth.views.password_change', {
        'template_name': 'password/change.html',
        'post_change_redirect': '/user/dash/'
    }, 'password_change'),

    url(r'^password/reset/?$', 'django.contrib.auth.views.password_reset', {
        'template_name': 'password/reset.html',
    }, 'password_reset'),

    url(r'^password/reset/done/?$', 'django.contrib.auth.views.password_reset_done', {
        'template_name': 'password/done.html',
    }),
    url(r'^password/reset/confirm/(?P<uidb36>[\w\d]+)/(?P<token>[-\w\d]+)/?$', 'django.contrib.auth.views.password_reset_confirm', {
        'template_name': 'password/confirm.html',
    }),
    url(r'^password/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', {
        'template_name': 'password/complete.html',
    }),

    url(r'^welcome/?$', 'users.views.basic_info', name="welcome"),
    url(r'^welcome/1/?$', 'users.views.charity_selection', name="welcome1"),
    url(r'^welcome/2/?$', 'users.views.giving_options', name="welcome2"),
    url(r'^welcome/3/?$', 'users.views.payment_details', name="welcome3"),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^button', include('button.urls', namespace='button')),

    url(r'^publisher', include('publishers.urls')),
    url(r'^charity', include('charities.urls')),

    url(r'^news', include('news.urls')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'', include('social_auth.urls')),
    url(r'^invites/', include('invites.urls', namespace='invites')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),


    url(r'^favicon\.ico$',
     RedirectView.as_view(url=staticfiles_storage.url("favicon.ico").replace("%","%%"))),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(prefix='/media/')

charities/urls.py
from django.conf.urls import patterns, include, url

specific = patterns('charities.views',
    url(r'^dash/?$', 'dash', name='dash'),
    url(r'^$', 'detail', name='detail'),
    url(r'^preference/?$', 'preference', name='preference')
)

collection = patterns('charities.views',
    url(r'^/?$', 'index', name='index')
)


urlpatterns = patterns('s',
    url(r'^/(?P<slug>[-_\w]+)/', include(specific, namespace='charity')),
    url(r'^/$', include(collection, namespace='charities'))
)

cover/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views import defaults

# These sometimes need to render in frames:
defaults.page_not_found = xframe_options_exempt(defaults.page_not_found)
defaults.server_error = xframe_options_exempt(defaults.server_error)
defaults.permission_denied = xframe_options_exempt(defaults.permission_denied)


urlpatterns = patterns('cover.views',
    url(r'^$', 'home', name='home'),
    url(r'^about/?$', 'about', name='about'),
    url(r'^terms/?$', 'terms', name='terms'),
    url(r'^faqs/?$', 'faqs', name='faqs'),
    url(r'^privacy_policy/?$', 'privacy_policy', name='privacy_policy'),
    url(r'^publisher_benefits/?$', 'publisher_benefits', name='publisher_benefits'),
    url(r'^charity_benefits/?$', 'charity_benefits', name='charity_benefits'),
    url(r'^community_benefits/?$', 'community_benefits', name='community_benefits'),
    url(r'^request_invite_code/?$', 'request_invite_code', name='request_invite_code'),
    url(r'^request_invite_code_success/?$', 'request_invite_code_success', name='request_invite_code_success'),
    url(r'^request_invite_code_failure/?$', 'request_invite_code_failure', name='request_invite_code_failure'),
)

news/urls.py
from django.conf.urls import patterns, include, url
#from news import views

urlpatterns = patterns('news.views',
    url(r'^/(?P<post_slug>[-_\w]+)/?$', 'post_detail', name='post'),
    url(r'^/$', 'post', name='posts'),
)

publishers/urls.py
from django.conf.urls import patterns, include, url

specific = patterns('publishers.views',
    url(r'^dash/?$', 'dash', name='dash')
)

collection = patterns('publishers.views',
    url(r'^signup/?$', 'signup', name='signup'),
    url(r'^/?$', 'publishers_landing', name='landing')
)

urlpatterns = patterns('',
    url(r'^/(?P<publisher_id>\d+)/', include(specific, namespace='publisher')),
    url(r'^/', include(collection, namespace='publishers')),
)

users/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('users.views',
    url(r'^dash/?$', 'dash', name='dash'),
)

cover/models.py
from django.db import models

# Create your models here.

cover/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from publishers.models import Publisher, URL
from charities.models import Charity
from mailchimp import utils

MAILCHIMP_LIST_ID = 'd8ef093bd4' # DRY :)
REDIRECT_URL_NAME = '/request_invite_code_success/'

def home(request):
    if request.user.is_authenticated():
        if request.user.is_publisher:
            return HttpResponseRedirect(
                reverse('users:dash'))
        else:
            return HttpResponseRedirect(reverse('publishers:landing'))
    else:
        try:
                email_address = request.POST['email']
                if request.method == 'POST':
                    list = utils.get_connection().get_list_by_id(MAILCHIMP_LIST_ID)
                    list.subscribe(email_address, {'EMAIL': email_address})
                    return HttpResponseRedirect('/request_invite_code_success/')
                else:
                    return HttpResponseRedirect('/request_invite_code_failure/')

        except:
                if request.method == 'GET':
                    return render(request, 'home.html', dict(
                        publishers=Publisher.objects.all(),
                        charities=Charity.objects.all(),
                        featured_publishers=Publisher.objects.filter(approved=True, featured=True)[:12],
                        contents=URL.objects.filter(total_donations_hc__gt=1).extra(order_by = ['-total_donations_hc'])[:10]
                        
                  
        ))

@login_required
def about(request):
    return render(request, 'about.html')

def terms(request):
    return render(request, 'terms.html')

def faqs(request):
    return render(request, 'faqs.html')

def privacy_policy(request):
    return render(request, 'privacy_policy.html')

def publisher_benefits(request):
    return render(request, 'publisher_benefits.html')

def charity_benefits(request):
    return render(request, 'charity_benefits.html')

def community_benefits(request):
    return render(request, 'community_benefits.html')

#This view is hacked together quickly with terrible error handling. Just needed to get somethinng out the door that works. 
def request_invite_code(request):
    try:
        email_address = request.POST['email']
        if request.method == 'POST':
            list = utils.get_connection().get_list_by_id(MAILCHIMP_LIST_ID)
            list.subscribe(email_address, {'EMAIL': email_address})
            return HttpResponseRedirect('/request_invite_code_success/')
        else:
            return HttpResponseRedirect('/request_invite_code_failure/')

    except:
        if request.method == 'GET':
            return render(request, 'request_invite_code.html')
        else:
            return HttpResponseRedirect('/request_invite_code_failure/')    

   
def request_invite_code_failure(request):
    return render(request, 'request_invite_code_failure.html')  

def request_invite_code_success(request):
    return render(request, 'request_invite_code_success.html')  

cover/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}CentUp{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta property="og:title" content="CentUp" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.centup.org" />
    <meta property="og:description" content="CentUp encourages us all to donate to content creators and charities at the click of a button. Help make the internet a better place." />
    <meta property="og:image" content="https://s3.amazonaws.com/centup_production/images/centup-fbimg.jpg" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="{% static 'main.css' %}" />

    <!-- webfonts -->
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <script src="{% static 'ext/modernizr.min.js' %}"></script>

    {% block head %}{% endblock head %}


</head>
<body>
    <!-- Adding Generic Bootstrap scaffold here -->
<div class="wrapper {% block pageclass %}{% endblock %}">
    <!-- Navigation -->
    <div class="container navbar-wrapper">
        <div class="navbar">
            <div class="navbar-inner">

                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="{% url 'home' %}">
                    <img src="{% static 'images/logo.png' %}" alt="CentUp" />
                </a>

                <div class="nav-collapse collapse">
                    <ul class="nav pull-right">

                        <style type="text/css">
                            .user-controls {
                                width: 500px;
                                height: 60px;
                                -webkit-border-radius: 8px;
                                border-radius: 8px;
                                -webkit-box-shadow:  0px 1px 8px 2px rgba(12, 12, 12, .1);
                                box-shadow:  0px 1px 8px 2px rgba(12, 12, 12, .1);
                                padding:9px;
                                background-color: hsla(0, 100%, 100%, 0.7);
                            }

                            .user-story {
                                width: 300px;
                                margin-left: 8px;
                            }

                            .user-story p {
                                font-size: 12px;
                            }

                            .orange {
                                color: #ECAA3E;
                            }

                            .aligner {
                                margin-top: 8px;
                                margin-left: 3px;
                            }

                            .settings {
                                border-left: 1px solid #666;
                                height: 60px;
                                padding-left: 8px;

                            }

                        </style>


                        <!--Building New User Header -->
                        {% if user.is_authenticated %}
                        <div class="user-controls">
                            <div class="avatar pull-left">
                                {% if user.large_avatar %}
                                    <img src="{{user.large_avatar.url}}" style="width:56px;height:56px;" alt="{{user}}'s Dashboard">
                                {% else %}
                                     <img src="{% static 'images/default_profile.gif' %}" style="width:56px;height:56px;" alt="">   
                                {% endif %}
                                
                            </div>

                            <div class="user-story pull-left">
                                <p>Oh hey {{user}},
                                you have <span class="orange">{{user.account.balance|floatformat:"0"}}</span> credits to split between 
                                {% if user.preferred_charity.active %}
                                <a href="{% url 'charity:detail' slug=user.preferred_charity.slug %}">{{user.preferred_charity}}</a> 
                                {% else %}
                                <a href="/charity">A charity of your choice</a> 
                                {% endif %}
                                and any of our great 
                                {% if request.get_full_path = "/publisher/" %}
                                content providers listed below
                                {% else %}
                                <a href="{% url 'publishers:landing' %}">content creators</a>
                                {% endif %}
                                !</p>
                            </div>
                           
                            <div class="settings pull-left ">
                                <ul>
                                    <li><a href="{% url 'users:dash' %}" id="current_user">My Account</a></li>
                                    {% if user.is_staff %}
                                        <li><a href="{% url 'admin:index' %}">Admin Site</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                                </ul>    

                            </div>

                        </div>
                        {% else %}
                            <a class="btn-custom" href="{% url 'signup' %}" >Sign Up</a> or 

                            <a href="{% url 'login' %}?{{REDIRECT_FIELD_NAME}}={{request.get_full_path}}">Login</a> 
                        {% endif %}
                        <!--End New User Header -->


                                  
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    </div><!-- /.container -->
    <div class="container" id="content">
	<div class="block">
        {% block content %}{% endblock %}
	</div>
    </div>

	<footer>
        <div class="container">
            <div class="row">
                <div class="span9">
                    <div class="pl">
                        <h3>About Us</h3>

                        <p>CentUp encourages us all to donate to creators and charities with the click of a button. Help make the internet a better place.</p>

                        <ul>
                            <li><a href="/faqs">FAQs</a></li>
                            <li><a href="http://centup.tumblr.com/" target="_blank">Blog</a></li>
                            
                        </ul>
                    </div>
                </div>

                <div class="span3">
                    <div class="pl">
                        <h3>Get in Touch</h3>

                        <ul>
                            <li><a href="{% url 'publishers:signup' %}">Become a Publisher</a></li>
                            <li><a href="/publisher_benefits">Publisher 101</a></li>
                            <li><a href="mailto:team@centup.org">Support</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row copyright">
                <div class="span12">

                    <p>&copy; 2013 Centup LLC. All Rights Reserved&nbsp;&nbsp;&bull;&nbsp;&nbsp;<a href="/terms">Terms and Conditions</a>&nbsp;&bull;&nbsp;<a href="/privacy_policy">Privacy Policy</a></p>

                </div>
            </div>
        </div>
    </footer>

</div>

    <!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="//browsehappy.com/">Upgrade your browser today</a> or <a href="//www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->

    <!-- Add your site or application content here -->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
 
    <script>
        window._csrftoken = "{{csrf_token}}";
    </script>

    <script>
        $(function ()
        { $(".question").popover({ trigger: "hover" });
        });
        //make bootstrap tabs persistant
        $(document).ready(function() {
            if (location.hash !== '') $('a[href="' + location.hash + '"]').tab('show');
            return $('a[data-toggle="tab"]').on('shown', function(e) {
              return location.hash = $(e.target).attr('href').substr(1);
            });

        });


        $(".clickme").click(function() {
            $('.video-container').fadeToggle('fast', function() {

            var iframe = "<iframe />";
            var id = $(this).attr('id'); // 
            var url = "http://player.vimeo.com/video/56722891?api=1&autoplay=1";

            var width = 840;
            var height = 500;
            var frameborder = 0;

             $(iframe, {
                name: 'videoframe',
                id: 'videoframe',
                src: url,
                width: width,
                height: height,
                frameborder: frameborder,
                type: 'text/html',
                allowfullscreen: true,
                webkitAllowFullScreen: true,
                mozallowfullscreen: true
            }).css({'position': 'relative'}).appendTo(this);

           
             });

        });

        $(document).ready(function(){
            $(".img-caption").hover(
                function(){
                    $(this).find('p').fadeIn();
                },          
                function(){
                    $(this).find('p').hide();
                }
            );

        });

        

        </script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script type="text/javascript">

    var _gaq = _gaq || []; 
    _gaq.push(['_setAccount', 'UA-33175865-1']); 
    _gaq.push(['_trackPageview']);

    (function() { 
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; 
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; 
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); 
    })();

    </script>
    <!--HTML5 Slider -->
    <script src="{% static 'ext/html5slider.js' %}"></script>
    <!--Bootstrap -->
    <script src="{% static 'ext/bootstrap/bootstrap-affix.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-alert.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-dropdown.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-tooltip.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-modal.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-transition.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-button.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-popover.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-typeahead.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-carousel.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-scrollspy.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-collapse.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-tab.js' %}"></script>
    <script src="{% static 'ext/bootstrap/bootstrap-fileupload.js' %}"></script>

    <script type="text/javascript">
    $('.carousel').carousel({
            interval: 1000
    })
    </script>


    <script src="{% static 'general.js' %}"></script>
    
   


</body>
</html>

cover/templates/charity_benefits.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}

{% endblock head %}

{% block content %}
	<div class="row white detail-page charity">
		<div class="generic-home-padding">

		<h1>Charity</h1>

		<p>Something Here...</p>

		</div>

	</div>
{% endblock content %}

cover/templates/community_benefits.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}

{% endblock head %}

{% block content %}
	<div class="row white detail-page charity">
		<div class="generic-home-padding">

		<h1>Community</h1>

		<p>Something Here...</p>

		</div>

	</div>
{% endblock content %}

cover/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}

<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.css" rel="stylesheet">

{% endblock head %}

{% block content %}

<style type="text/css">


.main-container {
    height:500px;
    background-color: #ccc;
    background: url({% static 'images/centup-back-2.png' %}) no-repeat;
}

.main-container h1 {
    color: #fff;
    font-weight: normal;
    font-size: 30px;
    line-height: 44px;
    text-shadow: 1px 1px 3px #1f1f1f;
        filter: dropshadow(color=#1f1f1f, offx=1, offy=1);
}

.feature_caption {
    display: none;
    position: absolute;
    top: 0px;
    left: 0px;
    height: 102px;
    width:102px;
    line-height: 110px;
    border: 4px solid #02ADEE;
   
}

.feature_caption span {
	color: #fff;
}

.signup-call-out {
	background-color: #ccc;

            border-bottom-right-radius: 8px;
            border-bottom-left-radius: 8px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;

}

.sidebar-list-2
    {
        list-style: none;
        margin:0;
    }
    
    .sidebar-list-2 li
    {
        float:left;
        width:60px;
        margin:0 10px 0 0;
    }
    
    .sidebar-list-2 li:nth-child(6n+1)
    {
        clear:left;
    }


    using-facebook a:hover {
    	color: #fff;
    }

    

</style>



<div class="container" id="content">
	
	<!--Start main container content-->
	<div class="block">
		<!--This is where the main page content goes-->
		<!--Start Video Container Content-->
		<div class="video-container block container">
			
			
		</div>
		<!--End Video Conatiner-->

		<!--Start Main Content Container Content-->
		<div class="row main-container signup">
			<div class="span9 generic-home-margin">
				<div class="generic-home-padding clickme">
					<div class="row1">
					<h1>Reward your favorite</h1></div>
					<div class="row2">
						<!-- Vertical Carousel -->
			        <div id="myCarousel" class="carousel slide vertical">
			            <!-- Carousel items -->
			            <div class="carousel-inner">
			                <div class="active item">
			                    <h1>bloggers</h1>
			                </div>
			                <div class="item">
			                    <h1>podcasters</h1>
			                </div>
			                <div class="item">
			                    <h1>comedians</h1>
			                </div>
			                <div class="item">
			                    <h1>videographers</h1>
			                </div>
			                <div class="item">
			                    <h1>photographers</h1>
			                </div>
			                <div class="item">
			                    <h1>illustrators
			                </div>
			                <div class="item">
			                    <h1>curators</h1>
			                </div>
			              
			            </div>		
			        </div>
			    </div>
			        
			    <!-- End Vertical Carousel -->
			    <div class="row3"><h1>and charities with the click<br> of a button.</h1></div><br><br><br><br><br><br><br><br>
					<div class="using-facebook">
					<p><b>Start Using CentUp Today</b></p>

					<p class="using-facebook">	
						<a class="using-facebook" href="{% url 'socialauth_begin' 'facebook' %}?{{ redirect_querystring }}">
							<button class="btn-large btn-facebook" ><i class="icon-facebook icon-white"></i> | Connect with Facebook</button></a></p><br><br>
						<br><br><br><br>
						<p>No Facebook?<br><a href="{% url 'signup' %}" >Sign Up via email</a></p>
						
					</div>
				<div>
			</div>
		</div>
		<!--End Main Content Conatiner-->


					
						
				</div>
			</div>
		</div>
		<!-- End Signup Row -->

		
		<!-- Homepage fun button 

			<div class="row white">
				<div class="span12">
					<div class="generic-home-padding">
						Test button here: 
						<div class="centup" data-url="http://localhost:5000" data-title="demo"></div>
						<script>
					    document.write('<script src="' + (
					        window.location.search ? window.location.search.slice(1) : 'http://localhost:5000'
					    ) + '/button.js"></scri'+'pt>');
					    </script>


					</div>
				</div>
			</div>


		End Homepage fun button -->



		<!--Top Content 

		<div class="row white">
			<div class="span12">
				<div class="generic-home-padding">
		
			<h2>Content</h2>

			<ul>
                    {% for content in contents %}
                    
                    <li>
                    	<a href="{{content.url}}" target="_blank">
                    		{{content.content}} 
                    	</a>

                    	
                    		{{content.total_donations|floatformat:"0"}}
                    		{{content.created_at|date:"SHORT_DATE_FORMAT"}}</time>
                    	
                    </li>
                        
                
                    {% endfor %}
           		</div>
			</div>
		</div>

		-->

		


		<!--Begin Charities, Communities Publishers Row-->
		<div class="row white benefits shadow-top">
			<center>
		<div class="row">
			<div class="span12">
				<div class="generic-home-padding">
					<h2>Every time you use CentUp, your cents are split evenly between your favorite creators and a charity. </h2><br>
					<h3>Here's just a sampling of creators where you can use the button:</h3>
				</div>
			</div>
		</div>	
		</center>
		<!--BEGIN Publisher List by approved and name -->
			<div class="row generic-home-padding publishers-list-home">
							<ul>
							{% for publisher in featured_publishers %}
								{% if publisher.approved %}
									<li>
					                    
					                    <div class="img-caption">
										{% if publisher.logo %}
					                    <a href="{{publisher.url}}" target="_blank"><img src="{{publisher.logo.url}}" style="width:110px;height:110px;" alt="{{publisher}}"></a>
					                    {% endif %}
										<a href="{{publisher.url}}" target="_blank" alt="{{publisher}}"><p id="feature-1-caption" class="feature_caption"><span></span></p></a>
										</div>

					                </li>

									{% else %}
								{% endif %}
							{% endfor %}
							</ul>
				
						<span class="clearfix"></span>
				
			</div>
		<!--END Publisher List by approved and name -->

		
		<div class="span12 beneftis">


			<div class="container">
    
			    <div class="row-fluid generic-home-padding">
			      <center>
			      	<h4>Or, learn how CentUp helps:</h4>
			   </center>

			
			</div>
			</div>

			<div class="span7 communities">
				<div class="benefits-container">

					<h3>Internet Lovers</h3>
					<p>Reading a new post on your favorite blog? Marveling at some wonderful instagram photography? Let amazing creators know that you support them with more than just a share. Using CentUp means you're helping content creators and charities do more. Best of all, you're taking an action that lets your favorite writers, musicians, podcasters, and more become YOUR biggest fans.</p>
					<!--<span><a class="button btn-custom" href="community.html">Share the Love</a></span>-->

				</div>
			</div>
			<div class="span5 benefits-img">
				<img src="{% static 'images/you.jpg' %}" />
			</div>
			<div class="span5 cl benefits-img">
				<img src="{% static 'images/publishers.jpg' %}" />
			</div>
			<div class="span7 publishers">
				<div class="benefits-container">
				<h3>Creators</h3>
				<p>Content creators deserve to make money from their work, but audiences today feel forced to pay, not necessarily motivated. CentUp changes behaviors by making social good a core element of the publishing business model.</p>

				<!--<span><a class="button btn-custom" href="/publisher">Earn Money</a></span>-->
				</div>
			</div>
			<div class="span7 charities cl">
				<div class="benefits-container">
					<h3>And Charities</h3>
					<p>One of the most common reasons people don't donate more online is because they forget. CentUp is an active reminder to give, and it lives where people are spending an enormous amount of time and attention each day: online.</p>
					<!--<span><a class="button btn-custom" href="{% url 'charities:index' %}">Attract Donors</a></span>-->

					<!--Insert Charity List -->
					<div>
						<div class="row">
							<ul class="sidebar-list-2">
							{% for charity in charities %}
								{% if charity.active %}
									<li>
										<a href="{{root_url}}/charity/{{charity.slug}}"><img src="{{charity.logo.url}}" style="width:50px;height:50px;" alt=""></a>
									</li>
								{% else %}
								{% endif %}
							{% endfor %}
							</ul>
						</div>
					</div>
					<!--Insert Charity List -->

				</div>

			</div>
			<div class="span5 benefits-img">
				<img src="{% static 'images/charities.jpg' %}" />
			</div>
		</div>

			<div class="row generic-home-padding borders">
						<div class="signup-call-out">
							<center>
							<span>Now are you ready to sign up?</span> <a class="using-facebook" href="{% url 'socialauth_begin' 'facebook' %}?{{ redirect_querystring }}"><button class="btn-large btn-facebook" ><i class="icon-facebook icon-white"></i> | Connect with Facebook</button></a> 
							</center>
						</div>

						<center>
							<p>- or - <a href="{% url 'signup' %}" >Sign Up via email</a></p>
						</center>	
					</div>
				</div>
			




	</div>
</div><!--End main container content-->



<script src="http://localhost:5000/button.js"></script>
{% endblock content %}