button/urls.py
from django.conf.urls import patterns, include, url
from  django.views.defaults import page_not_found

urlpatterns = patterns('button.views',
    url(r'^\.js$', 'button_script', name='script'),
    url(r'^/iframe/?$', 'button_iframe', name='iframe'),
    url(r'^/popup/$', page_not_found, name='popup_base'),
    url(r'^/popup/success/?$', 'success_popup', name='success_popup'),
    url(r'^/popup/extra/?$', 'extra_donation', name='extra_donation'),
    url(r'^/popup/error/?$', 'error_popup', name='error_popup'),
    url(r'^/popup/demo/?$', 'popup_demo', name='popup_demo'),
    url(r'^/code$', 'button_code', name='code'),
)

centup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# This effectly forces the admin site's login to just use the same
# login mechanics as everyone else
admin.site.login = login_required(admin.site.login)

admin.autodiscover()

publisher_patterns =patterns('')
invite_patterns =patterns('')

urlpatterns = patterns('',
    url(r'', include('cover.urls')),
    #url(r'^admintools/', include('admin_tools.urls')),

    url(r'^login/?$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html'
    }, 'login'),

    url(r'^invite/check/?$', 'invites.views.enter_invite_code', name=
        'enter_invite_code'),

    url(r'^signup/?$', 'users.views.basic_info', name='signup'),

    url(r'^logout/?$', 'django.contrib.auth.views.logout', {
        'next_page': '/'
    }, 'logout'),

    url(r'^password/change/?$', 'django.contrib.auth.views.password_change', {
        'template_name': 'password/change.html',
        'post_change_redirect': '/user/dash/'
    }, 'password_change'),

    url(r'^password/reset/?$', 'django.contrib.auth.views.password_reset', {
        'template_name': 'password/reset.html',
    }, 'password_reset'),

    url(r'^password/reset/done/?$', 'django.contrib.auth.views.password_reset_done', {
        'template_name': 'password/done.html',
    }),
    url(r'^password/reset/confirm/(?P<uidb36>[\w\d]+)/(?P<token>[-\w\d]+)/?$', 'django.contrib.auth.views.password_reset_confirm', {
        'template_name': 'password/confirm.html',
    }),
    url(r'^password/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', {
        'template_name': 'password/complete.html',
    }),

    url(r'^welcome/?$', 'users.views.basic_info', name="welcome"),
    url(r'^welcome/1/?$', 'users.views.charity_selection', name="welcome1"),
    url(r'^welcome/2/?$', 'users.views.giving_options', name="welcome2"),
    url(r'^welcome/3/?$', 'users.views.payment_details', name="welcome3"),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^button', include('button.urls', namespace='button')),

    url(r'^publisher', include('publishers.urls')),
    url(r'^charity', include('charities.urls')),

    url(r'^news', include('news.urls')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'', include('social_auth.urls')),
    url(r'^invites/', include('invites.urls', namespace='invites')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),


    url(r'^favicon\.ico$',
     RedirectView.as_view(url=staticfiles_storage.url("favicon.ico").replace("%","%%"))),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(prefix='/media/')

charities/urls.py
from django.conf.urls import patterns, include, url

specific = patterns('charities.views',
    url(r'^dash/?$', 'dash', name='dash'),
    url(r'^$', 'detail', name='detail'),
    url(r'^preference/?$', 'preference', name='preference')
)

collection = patterns('charities.views',
    url(r'^/?$', 'index', name='index')
)


urlpatterns = patterns('s',
    url(r'^/(?P<slug>[-_\w]+)/', include(specific, namespace='charity')),
    url(r'^/$', include(collection, namespace='charities'))
)

news/urls.py
from django.conf.urls import patterns, include, url
#from news import views

urlpatterns = patterns('news.views',
    url(r'^/(?P<post_slug>[-_\w]+)/?$', 'post_detail', name='post'),
    url(r'^/$', 'post', name='posts'),
)

button/models.py
from django.db import models

# Create your models here.

charities/models.py
from django.db import models

from users.models import User

class Charity(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=50, unique=True)
    logo = models.ImageField(upload_to='logos/charities/', blank=True)
    cover = models.ImageField(upload_to='cover/charities/', blank=True)
    url = models.CharField(max_length=128, blank=True)
    account = models.OneToOneField('accounts.Account', related_name='charity')
    short_description = models.TextField(blank=True)
    description = models.TextField()
    contact_info = models.TextField(blank=True)
    featured=models.BooleanField(default=False)
    active=models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'charities'


    def top_donors(self, since=None):
        donations = self.account.charity_donations_sources
        donations = donations.values('source_account').annotate(earnings_hc=models.Sum('charity_amount_hc'))
        if since:
            donations = donations.filter(created_at__gte=since)
        return donations.order_by('-earnings_hc')

    def top_publishers(self, since=None):
        donations = self.account.charity_donations_sources
        donations = donations.values('publisher_account').annotate(earnings_hc=models.Sum('charity_amount_hc'))
        if since:
            donations = donations.filter(created_at__gte=since)
        return donations.order_by('-earnings_hc')

#added a proper supporter count by listing all users where preferred charity = self   
    def supporter_count(self):
        objects =  list(User.objects.filter(preferred_charity=self))
        if len(objects) == 0:
            return "0"
        else:
            return len(objects)

            

button/views.py
import logging
logger = logging.getLogger(__name__)
from urlparse import urlparse

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from django.views.decorators.clickjacking import xframe_options_exempt

from accounts.models import Donation
from cover.templatetags import cents
from publishers.models import Publisher, URL

@login_required
def button_code(request):
    """Button code instructions for inclusion in publisher site"""

    return render(request, 'button/code.html', dict(
        script='<script src="%s%s"></script>' % (
                settings.PUBLIC_URL_ROOT,
                reverse('button:script')
            ),
        placeholder='<div class="centup"></div>',
        url_placeholder='<div class="centup" '
            'data-url="http://www.example.com/article/123" '
            'data-title="Article Title Here">'
            '</div>',
        tumblr_placeholder='<div class="centup" data-url="{Permalink}" data-title="{Title}"></div>'    
    ))

def button_script(request):
    """
    Render javascript for SCRIPT-tag included in
    publisher sites.

    This is actually a static file, but we want to show a "canonical"
    URL that won't change should the AWS url need to move around - so,
    for now, a simple redirect.
    """

    url = staticfiles_storage.url("button.js")

    return HttpResponsePermanentRedirect(url)


@xframe_options_exempt
def button_iframe(request):
    """Render button IFRAME container"""
    is_error_page = request.GET.get('error_page', False)
    try:
        url = URL.from_string(
            request.GET.get('url',
                request.META.get('HTTP_REFERER', None)
            ), title=request.GET.get('title', ''))
        if url is None:
            raise Exception("You must provide a URL for the CentUp button.")
        response =  render(request, 'button/button_frame.html', dict(
            url=url,
            problem=Donation.verify_donation(
                    user=request.user,
                    url=url,
                    amount="default"
                )
        ))
        if is_error_page:
            return HttpResponse(
                "Hmm... It seems that the error you were looking for has gone away.",
                content_type = 'text/plain'
            )

        else:
            return response

    except Exception, e:
        # Handle rendering of errors differently
        if is_error_page:
            raise
        error = "%s: %s" % (e.__class__, str(e))
        logger.exception(error)
        return render(request, 'button/button_error.html', dict(error=error))


@login_required
def success_popup(request):
    """Render post-donation success popup"""
    try:
        donation = get_object_or_404(Donation, pk=request.GET['donation'])
        if donation.source_account.user != request.user:
            raise PermissionDenied("Donation does not originate form this account")
        return  render(request, 'button/success.html', dict(
            max_donation=request.user.max_donation,
            amount=cents.credits(donation.amount),
            balance=cents.abbrev_credits(donation.url.total_donations),
            url=donation.url.url,
            title=donation.url.title,
            publisher=donation.publisher_account.publisher,
            charity=donation.charity_account.charity,
            acct_balance=cents.credits(request.user.account.balance),
        ))
    except Exception, e:
        error = "%s: %s" % (e.__class__, e)
        logger.exception(error)
        return render(request, 'button/popup_problem.html',
            dict(problem=error))

@require_POST
@login_required
def extra_donation(request):
    try:
        donation = Donation.register(
                user=request.user,
                url=request.POST['url'],
                amount=int(request.POST['extra_donation'])
            )
        return render(request, 'button/thanks.html', dict(
                action='extra',
                amount=cents.credits(donation.amount),
                balance=cents.abbrev_credits(donation.url.total_donations),
                charity=donation.charity_account.charity,
                publisher=donation.publisher_account.publisher,
                long_url=donation.url.url,
                title=donation.url.title
            ))
    except Exception, e:
        error = "%s: %s" % (e.__class__, e)
        logger.exception(error)
        return render(request, 'button/popup_problem.html',
            dict(problem=error))

@xframe_options_exempt
def popup_demo(request):
    return render(request, 'button/popup_demo.html')

@xframe_options_exempt
def error_popup(request):
    return render(request, 'button/popup_problem.html')



charities/views.py
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from charities.models import Charity
from users.models import User
from publishers.models import Publisher
from users import forms

DEFAULT_EARNERS_WINDOW=timedelta(days=90)

def dash(request, charity_slug):
    charity = get_object_or_404(Charity, pk=charity_id)
    data_since = datetime.now() - DEFAULT_EARNERS_WINDOW
    return render(request, 'charity/dash.html', dict(
        charity=charity,
        top_donors=_iter_top_donors(
            charity.top_donors(since=data_since)
        ),
        top_publishers=_iter_top_publishers(
            charity.top_publishers()
        )
    ))


def _iter_top_donors(qs):
    for donor in qs:
        yield User.objects.get(account=donor['source_account']), donor['earnings_hc'] / 2.0

def _iter_top_publishers(qs):
    for pub in qs:
        yield Publisher.objects.get(account=pub['publisher_account']), pub['earnings_hc'] / 2.0


def index(request):
    return render(request, 'charity/index.html', dict(
        charities=Charity.objects.all(),
    ))

@require_POST
@login_required
def preference(request, slug):
    charity = get_object_or_404(Charity, slug=slug)
    request.user.preferred_charity = charity;
    request.user.save()
    return HttpResponse('ok', 'text/plain')



def detail(request, slug):
    charity = get_object_or_404(Charity, slug=slug)
    data_since = datetime.now() - DEFAULT_EARNERS_WINDOW

    return render(request, 'charity/detail.html', dict(
        charity = charity,
        top_donors=_iter_top_donors(
            charity.top_donors(since=data_since)
        )
    ))

charities/templates/charity/button.html
{% if user.is_authenticated %}
    <button class="btn-custom ajax selector{% if user.preferred_charity == charity %} selected{% endif %}" formaction="{% url 'charity:preference' slug=charity.slug %}" formmethod="POST">
        Charity
    </button>
{% endif %}

charities/templates/charity/dash.html
{% extends "base.html" %}
{% load cents %}
{% block title %}
    {{charity}} - Dashboard
{% endblock title %}
{% block content %}
<div class="white ">
    <div class="generic-home-padding">
    <h1>{{charity}} Dashboard</h1>
    <p>{{charity.description}}</p>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
        <li><a href="#history" data-toggle="tab">History</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="overview">

                    <div class="row">
                   <div class="span4">
                    <h4>Your Organization</h4>
                    {% if charity.logo.url %}
                    <img src="{{charity.logo.url}}" style="width:250px;height:100px" title="{{charity}}"/>
                    {% else %}
                    no image here. how did this happen..
                    {% endif %}
                    </div>

                    <div class="span4">
                    <h4>Gifts Waiting to Be Cashed</h4>
                    <p>{{charity.account.balance|dollars}}</p>
                    </div>

                    <div class="span3">
                    <h4>Total Gifts</h4>
                    {{charity.account.balance|dollars}}
                     </div>
                     </div>

        </div>
        <div class="tab-pane" id="history">
           FANCY GRAPH
        </div>
    </div>

    <div class="row">
        <div class="span6">
            <div class="generic-home-padding">
                <h3>Top Donors (Last 90 Days)</h3>
                <table class="table">
                    <tbody>
                        {% for donor, earnings in top_donors %}
                        <tr>
                            <th>
                                {{donor}}
                            </th>
                            <td>
                                {{earnings|dollars}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="span6">
            <div class="generic-home-padding">
            <h3>Top Publishers Earning Gifts</h3>
            <table class="table table-bordered table-striped">
                <tbody>
                    {% for publisher, amount in top_publishers %}
                    <tr>
                        <th>
                            {{publisher}}
                        </th>
                        <td>
                           {{amount|dollars}}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
</div>


{% endblock content %}

charities/templates/charity/detail.html
{% extends "base.html" %}
{% load cents %}
{% load staticfiles %}
{% block title %}
    Centup Charity - {{charity.name}}
{% endblock title %}

{% block pageclass %}content-page{% endblock pageclass %}

{% block content %}

<div class="row white detail-page charity">
    <div class="span9">
        <div class="row detail-header" style="{% if charity.cover %}background-image: url('{{charity.cover.url}}');{% endif %}">

            {% if charity.logo %}
                <img src="{{charity.logo.url}}" width="125" class="logo">
            {% else %}
                <img src="{% static 'images/default_profile.gif' %}" alt="Lincoln">
            {% endif %}

            <div class="detail-header-details">
                <h1>{{charity.name}}</h1>
                <a href="{{charity.url}}" target="_blank">{{charity.url}}</a>

                {% include "charity/button.html" %}
            </div>
        </div>
        <div class="row content-page">
            <h2>About {{charity.name}}</h2>
            
            {% autoescape off %}
            {{charity.description|linebreaks}}
            {% endautoescape %}

        </div>
        
    </div>

    <div class="span3 detail-asside">

        <div class="detail-details">
            <h4>This Month</h4>
            <p class="featured-cents">{{charity.account.balance|dollars}}</p>
            <p class="ico-supporters"><b>{{ charity.supporter_count }}</b> supporters</p>
        </div>


        <div class="asside-list">
            <h3>Top Donors</h3>
            {% for donor, earnings in top_donors %}
            <div class="asside-li">
                {% if donor.large_avatar %}
                    <img src="{{donor.large_avatar.url}}" alt="" width="28">
                {% else %}
                    <img src="{% static 'images/default_profile.gif' %}" alt="" width="28">
                {% endif %}

                
                {% if donor.first_name and donor.last_name %}
                    {{ donor.first_name }} {{ donor.last_name }}</a>
                {% else %}
                    {{ donor.username }}
                {% endif %}
                
                <br>
                {{earnings|dollars}}
            </div>
            {% endfor %}
        </div>

    </div>
</div>





{% endblock content %}

charities/templates/charity/index.html
{% extends "base.html" %}
{% load cents %}
{% block title %}
    Centup Charities
{% endblock title %}

{% block pageclass %}content-page{% endblock pageclass %}

{% block content %}
<div class="general-page generic-home-padding white clearfix">
    <h1>Centup Charities</h1>

    {% include "charity/selector.html" with link_to_details=True %}
</div>

{% endblock content %}

charities/templates/charity/selector.html
<div class="charities listing clearfix">
    {% for charity in charities %}
        {% if charity.active %}
            <div class="charity">
                <h2 class="name">{{charity.name}}</h2>
                {% if link_to_details %}
                    <a href="{% url 'charity:detail' slug=charity.slug %}">
                {% endif %}
                {# #TODO use default logo if none is added #}
                <img src="{{charity.logo.url}}" class="logo" />
                {% if link_to_details %}
                    </a>
                {% endif %}
                {% include "charity/button.html" %}
                <p class="description">
                    {{charity.short_description}}
                </p>
                {% if link_to_details %}
                    <p class="more">
                        <a href="{% url 'charity:detail' slug=charity.slug %}">
                            Read more &raquo;
                        </a>
                    </p>
                {% endif %}
            </div>
            {% endif %}
    {% endfor %}
</div>