accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('accounts.views',
    url(r'^centup$', 'centup', name='centup'),
)

button/urls.py
from django.conf.urls import patterns, include, url
from  django.views.defaults import page_not_found

urlpatterns = patterns('button.views',
    url(r'^\.js$', 'button_script', name='script'),
    url(r'^/iframe/?$', 'button_iframe', name='iframe'),
    url(r'^/popup/$', page_not_found, name='popup_base'),
    url(r'^/popup/success/?$', 'success_popup', name='success_popup'),
    url(r'^/popup/extra/?$', 'extra_donation', name='extra_donation'),
    url(r'^/popup/error/?$', 'error_popup', name='error_popup'),
    url(r'^/popup/demo/?$', 'popup_demo', name='popup_demo'),
    url(r'^/code$', 'button_code', name='code'),
)

centup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# This effectly forces the admin site's login to just use the same
# login mechanics as everyone else
admin.site.login = login_required(admin.site.login)

admin.autodiscover()

publisher_patterns =patterns('')
invite_patterns =patterns('')

urlpatterns = patterns('',
    url(r'', include('cover.urls')),
    #url(r'^admintools/', include('admin_tools.urls')),

    url(r'^login/?$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html'
    }, 'login'),

    url(r'^invite/check/?$', 'invites.views.enter_invite_code', name=
        'enter_invite_code'),

    url(r'^signup/?$', 'users.views.basic_info', name='signup'),

    url(r'^logout/?$', 'django.contrib.auth.views.logout', {
        'next_page': '/'
    }, 'logout'),

    url(r'^password/change/?$', 'django.contrib.auth.views.password_change', {
        'template_name': 'password/change.html',
        'post_change_redirect': '/user/dash/'
    }, 'password_change'),

    url(r'^password/reset/?$', 'django.contrib.auth.views.password_reset', {
        'template_name': 'password/reset.html',
    }, 'password_reset'),

    url(r'^password/reset/done/?$', 'django.contrib.auth.views.password_reset_done', {
        'template_name': 'password/done.html',
    }),
    url(r'^password/reset/confirm/(?P<uidb36>[\w\d]+)/(?P<token>[-\w\d]+)/?$', 'django.contrib.auth.views.password_reset_confirm', {
        'template_name': 'password/confirm.html',
    }),
    url(r'^password/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', {
        'template_name': 'password/complete.html',
    }),

    url(r'^welcome/?$', 'users.views.basic_info', name="welcome"),
    url(r'^welcome/1/?$', 'users.views.charity_selection', name="welcome1"),
    url(r'^welcome/2/?$', 'users.views.giving_options', name="welcome2"),
    url(r'^welcome/3/?$', 'users.views.payment_details', name="welcome3"),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^button', include('button.urls', namespace='button')),

    url(r'^publisher', include('publishers.urls')),
    url(r'^charity', include('charities.urls')),

    url(r'^news', include('news.urls')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'', include('social_auth.urls')),
    url(r'^invites/', include('invites.urls', namespace='invites')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),


    url(r'^favicon\.ico$',
     RedirectView.as_view(url=staticfiles_storage.url("favicon.ico").replace("%","%%"))),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(prefix='/media/')

charities/urls.py
from django.conf.urls import patterns, include, url

specific = patterns('charities.views',
    url(r'^dash/?$', 'dash', name='dash'),
    url(r'^$', 'detail', name='detail'),
    url(r'^preference/?$', 'preference', name='preference')
)

collection = patterns('charities.views',
    url(r'^/?$', 'index', name='index')
)


urlpatterns = patterns('s',
    url(r'^/(?P<slug>[-_\w]+)/', include(specific, namespace='charity')),
    url(r'^/$', include(collection, namespace='charities'))
)

news/urls.py
from django.conf.urls import patterns, include, url
#from news import views

urlpatterns = patterns('news.views',
    url(r'^/(?P<post_slug>[-_\w]+)/?$', 'post_detail', name='post'),
    url(r'^/$', 'post', name='posts'),
)

users/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('users.views',
    url(r'^dash/?$', 'dash', name='dash'),
)

button/models.py
from django.db import models

# Create your models here.

button/views.py
import logging
logger = logging.getLogger(__name__)
from urlparse import urlparse

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from django.views.decorators.clickjacking import xframe_options_exempt

from accounts.models import Donation
from cover.templatetags import cents
from publishers.models import Publisher, URL

@login_required
def button_code(request):
    """Button code instructions for inclusion in publisher site"""

    return render(request, 'button/code.html', dict(
        script='<script src="%s%s"></script>' % (
                settings.PUBLIC_URL_ROOT,
                reverse('button:script')
            ),
        placeholder='<div class="centup"></div>',
        url_placeholder='<div class="centup" '
            'data-url="http://www.example.com/article/123" '
            'data-title="Article Title Here">'
            '</div>',
        tumblr_placeholder='<div class="centup" data-url="{Permalink}" data-title="{Title}"></div>'    
    ))

def button_script(request):
    """
    Render javascript for SCRIPT-tag included in
    publisher sites.

    This is actually a static file, but we want to show a "canonical"
    URL that won't change should the AWS url need to move around - so,
    for now, a simple redirect.
    """

    url = staticfiles_storage.url("button.js")

    return HttpResponsePermanentRedirect(url)


@xframe_options_exempt
def button_iframe(request):
    """Render button IFRAME container"""
    is_error_page = request.GET.get('error_page', False)
    try:
        url = URL.from_string(
            request.GET.get('url',
                request.META.get('HTTP_REFERER', None)
            ), title=request.GET.get('title', ''))
        if url is None:
            raise Exception("You must provide a URL for the CentUp button.")
        response =  render(request, 'button/button_frame.html', dict(
            url=url,
            problem=Donation.verify_donation(
                    user=request.user,
                    url=url,
                    amount="default"
                )
        ))
        if is_error_page:
            return HttpResponse(
                "Hmm... It seems that the error you were looking for has gone away.",
                content_type = 'text/plain'
            )

        else:
            return response

    except Exception, e:
        # Handle rendering of errors differently
        if is_error_page:
            raise
        error = "%s: %s" % (e.__class__, str(e))
        logger.exception(error)
        return render(request, 'button/button_error.html', dict(error=error))


@login_required
def success_popup(request):
    """Render post-donation success popup"""
    try:
        donation = get_object_or_404(Donation, pk=request.GET['donation'])
        if donation.source_account.user != request.user:
            raise PermissionDenied("Donation does not originate form this account")
        return  render(request, 'button/success.html', dict(
            max_donation=request.user.max_donation,
            amount=cents.credits(donation.amount),
            balance=cents.abbrev_credits(donation.url.total_donations),
            url=donation.url.url,
            title=donation.url.title,
            publisher=donation.publisher_account.publisher,
            charity=donation.charity_account.charity,
            acct_balance=cents.credits(request.user.account.balance),
        ))
    except Exception, e:
        error = "%s: %s" % (e.__class__, e)
        logger.exception(error)
        return render(request, 'button/popup_problem.html',
            dict(problem=error))

@require_POST
@login_required
def extra_donation(request):
    try:
        donation = Donation.register(
                user=request.user,
                url=request.POST['url'],
                amount=int(request.POST['extra_donation'])
            )
        return render(request, 'button/thanks.html', dict(
                action='extra',
                amount=cents.credits(donation.amount),
                balance=cents.abbrev_credits(donation.url.total_donations),
                charity=donation.charity_account.charity,
                publisher=donation.publisher_account.publisher,
                long_url=donation.url.url,
                title=donation.url.title
            ))
    except Exception, e:
        error = "%s: %s" % (e.__class__, e)
        logger.exception(error)
        return render(request, 'button/popup_problem.html',
            dict(problem=error))

@xframe_options_exempt
def popup_demo(request):
    return render(request, 'button/popup_demo.html')

@xframe_options_exempt
def error_popup(request):
    return render(request, 'button/popup_problem.html')



button/templates/button/button_error.html
{% load utils %}
<!doctype html>
<html>
<head>

    <style type="text/css">
        body {
            font-size:50%;
            text-transform: uppercase;
            text-align:center;
            margin:0;
        }
        a {
            text-decoration: none;
            color: blue;
        }
    </style>
</head>
<body>
    <a title="Error: {{error}}" href="{% addurlparameter 'error_page' 'yes' %}" target="_top">Error loading centup button </a>
</body>
</html>

button/templates/button/button_frame.html
{% load staticfiles %}
{% load cents %}
<!doctype html>
<html>
	<head>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<link rel="stylesheet" href="{% static 'button/button.css' %}">
		<script src="{% static 'button/button.js' %}"></script>
	</head>
	<body>
		<div id="container" data-posthref="{% url 'accounts:centup' %}" data-popuphref="{% url 'button:success_popup' %}" data-errorhref="{% url 'button:error_popup' %}" data-demohref="{% url 'button:popup_demo' %}" data-url="{{url.url}}" data-csrftoken="{{csrf_token}}" title="{{problem.message}}"><div id="button"><span class="button-text">CentUp</span></div>​<i class="arrow"></i><s class="arrow cover"></s>
			<div id="balance">{{url.total_donations|abbrev_credits}}</div>
		</div>
	</body>
</html>

button/templates/button/code.html
{% extends "base.html" %}
{% block title %}
    CentUp button setup
{% endblock title %}

{% block head %}
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&skin=sons-of-obsidian"></script>
{% endblock head %}

{% block content %}

<style type="text/css">
    .form-stretch {
        width:90%;
        background-color: #eee;
    }

    .tall {
        height: 260px;
    }

</style>

<div class="general-page generic-home-padding white">
<h1>Setting up your CentUp button</h1>
<h3>All Users</h3>
<ol>
    <li>
        <p>Include the CentUp script at the end of your page, just before the body tag:</p>
        <pre class="prettyprint linenums">{{script}}</pre>
    </li>

    <li>
        <p>Place the following code wherever you want the CentUp button to appear:</p>
        <pre class="prettyprint linenums">{{placeholder}}</pre>

        <p>By default, this will assign the CentUp to the current URL and use the current page's title. However, you can specify your own URL and title using the <tt>data-url</tt> and <tt>data-title</tt> attributes respectively. This may be necessary if you are showing multiple articles on the same page, each with their own CentUp button. For example:</p>
        <pre class="prettyprint linenums">{{url_placeholder}}</pre>
    </li>
          
</ol>

<h3>Tumblr Users</h3>
<ol>
    <li>Login to Tumblr</li>
    <li>In a new tab, go to your Tumblr site</li>
    <li>In the upper right corner, click the "Customize" button</li>
    <li>On the left side bar, click "Edit HTML"</li>
    <li>Scroll down until you find the Text Post section</li>
    <li>
        <p>Paste the code below after   &lt;div class=metadata&gt; (or wherever you want this to go on the post)</p>
       <pre class="prettyprint linenums">{{tumblr_placeholder}}</pre>
    </li>
    <li>Repeat the above step for each kind of post (photo, quote, link, video, etc.) that you use on your Tumblr</li>
    <li>Scroll down until your find "&lt;/body&gt;"</li>
    <li>
        <p>Paste the this code just before "&lt;/body&gt;"</p>
        <pre class="prettyprint linenums">&lt;script src="https://www.centup.org/button.js"&gt;&lt;/script&gt;</pre>
    </li>
    <li>Click the green "Update Preview" button at the top of the page</li>
    <li>Click the green "Save" button next to "Update Preview"</li>
</ol>

<h3>Wordpress Users (Self-Hosted)</h3>
<ol>
    <li>Login to your Wordpress site.</li>

    <li>From the dashboard, in the left sidebar click "appearance" then "editor"</li>
    <li>Make sure your theme is selected in the "Select theme to edit" drop down</li>
    <li>Under "Theme Files" on the right, select "functions.php"</li>
    <li><p>Paste the following code on a line after "&lt;?php":</p>
       <pre class="prettyprint linenums">
// ¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢
// add CentUp Button
// ¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢

function add_centup_button($content) {
	$cu_content .= '&lt;div class="centup" data-url="' . post_permalink() . '"data-title="' . get_the_title() . '"&gt;&lt;/div&gt;';
	$cu_content .= $content;
	return $cu_content;
}
add_filter('the_content', 'add_centup_button');

function add_centup_js(){
    echo '&lt;script src="https://www.centup.org/button.js"&gt;&lt;/script&gt;';
}
add_action('wp_footer', 'add_centup_js');

// ¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢
// end CentUp Button
// ¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢¢</pre>
    </li>

    <li>Click "Update File"</li>
</ol>

<h3>Blogger Users</h3>
<ol>
    <li>Login to blogger, and select your blog.</li>
    <li>From your blog overview page, click "Template" in the left column.</li>
    <li>Click the "Edit HTML" button under your live template</li>
    <li>Find "&lt;/body&gt;" toward the bottom of your template. (To find it quickly, search for it using command + F or control + F)</li>
    <li><p>Paste this code on the line before the "&lt;/body&gt;" tag</p>
      <pre class="prettyprint linenums">&lt;script src='https://www.centup.org/button.js'/&gt;</pre>
    </li>
    <li>Click the "Jump to widget" button and select "Blog 1"</li>
    <li>Click the black arrow next to the line number to expand the code if it isn't already.</li>
    <li>Find "id='shareButtons'" and click the black arrow next to the line number to expand the code if it isn't already</li>
    <li><p>Find "&lt;b:if cond='data:top.showDummy'&gt;" and paste this code on the line before it:</p>
        <pre class="prettyprint linenums">&lt;div class='centup' expr:data-title='data:post.title' expr:data-url='data:post.url'&gt;&lt;/div&gt;</pre></li>
<li>Click the "Save template" button</li>


</div>
{% endblock content %}

button/templates/button/popup.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <title>CentUp Button</title>
     <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
     <link href='//fonts.googleapis.com/css?family=Montserrat+Alternates:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'button/popup.css' %}">
    <script src="{% static 'ext/html5slider.js' %}"></script>
    {% block head %}{% endblock head %}

<style type="text/css">
	body {
		background-color: #fff;
	}

	#content {
		background-color: #fff;
	}

    .popup-myacct {
        font-size: 12px;
        color: #666;
    }
	
</style>

</head>
<body>
    <div class="popup-container">
        <div class="popup-head">
            <div class="popup-logo"><img src="{% static 'images/cent-icon.png' %}"></div>
            <div class="popup-logo-text">CentUp</div>

            {% if user.is_authenticated %}
            <div class="popup-myacct">
                <a href="{{root_url}}/publisher" target="_blank">Where Can I use CentUp?</a> |
                <a href="{% url 'users:dash' %}" target="_blank" id="go2account">My Account</a>
            </div>
            {% else %}
            <div class="popup-myacct">
                <a href="{% url 'login' %}?{{REDIRECT_FIELD_NAME}}={{request.get_full_path}}">Login</a> 
            </div>
            {% endif %}

        </div>

        <div class="popup-body">
            {% block content %}{% endblock content %}
        </div>

        <div class="popup-footer">
            <a href="/terms" target="_blank">CentUp Terms & Conditions</a>
        </div>  

    </div>
        <!-- Google Analytics -->
            <script type="text/javascript">
                var _gaq = _gaq || []; 
                _gaq.push(['_setAccount', 'UA-33175865-1']); 
                _gaq.push(['_trackPageview']);

                (function() { 
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; 
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; 
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); 
                })();
            </script>
</body>
</html>

button/templates/button/popup_demo.html
{% extends "button/popup.html" %}

{% block head %}
        <script>
            var slider;
            $(function(ev) {
                $(".popup-slider input").on('change', updateCounter);
                updateCounter();

            })
            function updateCounter() {
                var value = Number($(".popup-slider input").val());
                $("#counter").html("&cent;" + value);
            }
            $('#go2account').on('click', function(){ window.close(); });


                window.twttr = (function (d,s,id) {
                  var t, js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
                  js.src="https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
                  return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
                }(document, "script", "twitter-wjs"));


        </script>
        <!--Shitty CSS overide-->
        <style type="text/css">
            .popup-increase-container {
                margin-top: -10px;
            }
        </style>


{% endblock head %}
{% block content %}


        <h1>The Real Button is Even Easier</h1>
        <p>You could have just split <span class="popup-amount">25 CentUp credits</span>(or any amount you setup)between a publisher and charity of your choice. 
            
        </p>
            <p>
                <a href="http://twitter.com/intent/tweet?text=I just gave a few cents to {{title}} - {{url}}&url=/" class="twitter-share-button" data-count="none">Tweet</a>
                
            </p>
        <div class="popup-increase-container">
            <h2>And if that wasn't enough, you can always donate more:</h2>
            <form action="{% url 'button:extra_donation' %}" method="post">
                <div class="slider-container">
	                <div class="popup-slider">
	                    <input type="range" name="extra_donation" value="0" max="100" />
	                </div>
	                <div class="popup-counter">
	                    <div id="counter">.0</div>
	                    <input type="hidden" name="url" value="{{url}}" />
	                    {% csrf_token %}
	                </div>
                    <div class="available"> 0<br>available</div>
	                <div class="clear-fix"> </div>
                </div>
                <div class="popup-increase">
	                <input type="submit" class="btn-custom" value="Increase!"> 
                    <a href="javascript:window.close()">No thanks</a>
                </div>
            </form>
           
        </div>


{% endblock content %}

button/templates/button/popup_problem.html
{% extends "button/popup.html" %}
{% block head %}
    <script>
    $(function(){
        $('#url').click(function() { window.opener() });
        //a crappy hack for rendering errors from the caller's JS
        //without resorting to a very XSS-able param
        var errorInfo = window.opener._centupErrorInfo;
        if( $("#problem").html() === "" && errorInfo !== undefined ) {
            $("#problem").text(errorInfo.message);
            if( errorInfo.title !== undefined ) {
                $("#title").text(errorInfo.title);
            };
            if( errorInfo.url !== undefined ) {
                $("#url").attr('href', errorInfo.url);
                $("#url").html((errorInfo.urlText|| ""))
            };
            if( errorInfo.hackyExtra !== undefined) {
                $("#url").after(errorInfo.hackyExtra);
            };
        }
    })
    </script>

{% endblock head %}
{% block content %}
    <h1>Oh hey...</h1>
    <p id="problem">{{problem}}</p>
    <a href="" id="url" target="_blank"></a>
{% endblock content %}

button/templates/button/success.html
{% extends "button/popup.html" %}

{% block head %}
        <script>
            var slider;
            $(function(ev) {
                $(".popup-slider input").on('change', updateCounter);
                updateCounter();

            })
            function updateCounter() {
                var value = Number($(".popup-slider input").val());
                $("#counter").html("&cent;" + value);
            }
            $('#go2account').on('click', function(){ window.close(); });


                window.twttr = (function (d,s,id) {
                  var t, js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
                  js.src="https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
                  return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
                }(document, "script", "twitter-wjs"));


        </script>
        <!--Shitty CSS overide-->
        <style type="text/css">
            .popup-increase-container {
                margin-top: -10px;
            }
        </style>


{% endblock head %}
{% block content %}


        <h1>Thank You!</h1>
        <p>You just donated <span class="popup-amount">{{amount}} CentUp credits</span>.
            Your pledge will be split evenly between
            <span class="publisher">
                <a href="{{publisher.url}}" target="_blank">{{publisher}}</a>                
            </span>
            and 
            <span class="publisher">
                <a href="{% url 'charity:detail' slug=charity.slug %}" target="_blank">{{charity}}</a>    
            </span>
            .
        </p>
            <p>
                <a href="http://twitter.com/intent/tweet?text=I just gave a few cents to {{title}} - {{url}}&url=/" class="twitter-share-button" data-count="none">Tweet</a>
                
            </p>
        <div class="popup-increase-container">
            <h2>Donate more?</h2>
            <form action="{% url 'button:extra_donation' %}" method="post">
                <div class="slider-container">
	                <div class="popup-slider">
	                    <input type="range" name="extra_donation" value="0" max="100" />
	                </div>
	                <div class="popup-counter">
	                    <div id="counter">.0</div>
	                    <input type="hidden" name="url" value="{{url}}" />
	                    {% csrf_token %}
	                </div>
                    <div class="available"> {{acct_balance}}<br>available</div>
	                <div class="clear-fix"> </div>
                </div>
                <div class="popup-increase">
	                <input type="submit" class="btn-custom" value="Increase!"> 
                    <a href="javascript:window.close()">No thanks</a>
                </div>
            </form>
           
        </div>


{% endblock content %}

button/templates/button/thanks.html
{% extends "button/popup.html" %}
{% block head %}
    <script>
    $(function() {
        window.opener.showCentup({
            action: '{{action|escapejs}}',
            amount: '{{amount|escapejs}}',
            balance:'{{balance|escapejs}}',
            charity:'{{charity|escapejs}}',
            pubisher:'{{publisher|escapejs}}',
            title:'{{title|escapejs}}',
        });
    });
    </script>


    <script type="text/javascript">
        window.twttr = (function (d,s,id) {
          var t, js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
          js.src="https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
          return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
        }(document, "script", "twitter-wjs"));

    </script>

    
{% endblock head %}
{% block content %}

    <h1>Thanks for making the world gooder, much gooder.</h1>
    <p>Tell your friends so they can donate too!</p>

    <a href="http://twitter.com/intent/tweet?text=I just gave a few cents to {{title}} - {{long_url}}&url=/" class="twitter-share-button" data-count="none">Tweet</a>

    

    
    <p><a href="javascript:window.close();" id="close">Close Window</a></p>
{% endblock content %}